from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from annotate_v2_batch_1 import build_test_case, load_candidates


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data" / "seed" / "v2_annotated_3.json"


KEPT: list[dict[str, Any]] = [
    {
        "candidate_id": "v2_087",
        "category": "corporate",
        "sector": "军工电子/半导体参股",
        "key_entities": ["宏达电子", "江苏展芯", "创业板IPO"],
        "key_numbers": ["13.79%", "2025年12月18日"],
        "expected_direction": "down",
        "subcategory": "参股公司IPO澄清",
        "memorization_likelihood": "medium",
        "target": "宏达电子",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_088",
        "category": "corporate",
        "sector": "券商",
        "key_entities": ["天风证券", "湖北宏泰集团"],
        "key_numbers": ["40亿元", "5%", "4%", "展期一年"],
        "expected_direction": "up",
        "subcategory": "关联债务展期降息",
        "memorization_likelihood": "low",
        "target": "天风证券",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_089",
        "category": "macro",
        "sector": "A股宽基/科技制造",
        "key_entities": ["高盛", "中国A股", "中国H股", "半导体"],
        "key_numbers": ["过去三个月", "高配"],
        "expected_direction": "up",
        "subcategory": "外资机构看多中国资产",
        "memorization_likelihood": "medium",
        "target": "沪深300指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000300",
    },
    {
        "candidate_id": "v2_090",
        "category": "industry",
        "sector": "低空经济/半导体会展",
        "key_entities": ["上海国际低空经济产业大会", "湾区半导体产业生态博览会", "海光信息"],
        "key_numbers": ["10月15日至17日", "三季报"],
        "expected_direction": "up",
        "subcategory": "投资日历/产业大会催化",
        "memorization_likelihood": "medium",
        "target": "低空经济板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_091",
        "category": "industry",
        "sector": "AI/并购重组",
        "key_entities": ["上纬新材", "天普股份", "AI概念股", "并购概念股"],
        "key_numbers": ["528只", "124只", "6只", "4倍多"],
        "expected_direction": "up",
        "subcategory": "年度牛股复盘",
        "memorization_likelihood": "medium",
        "target": "AI与并购概念股",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_092",
        "category": "industry",
        "sector": "数字经济/信创",
        "key_entities": ["科创信息", "英飞拓", "国脉科技", "拓维信息"],
        "key_numbers": ["3连板"],
        "expected_direction": "up",
        "subcategory": "数字经济主线强化",
        "memorization_likelihood": "low",
        "target": "科创信息",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300730",
    },
    {
        "candidate_id": "v2_093",
        "category": "industry",
        "sector": "大金融/科技成长",
        "key_entities": ["创业板指", "东方财富", "大金融", "半导体"],
        "key_numbers": ["涨超4%", "涨近10%"],
        "expected_direction": "up",
        "subcategory": "市场主线强化",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sz399006",
    },
    {
        "candidate_id": "v2_094",
        "category": "corporate",
        "sector": "射频前端/半导体",
        "key_entities": ["唯捷创芯", "L-PAMiD", "头部品牌客户"],
        "key_numbers": ["量产出货", "6月底库存改善", "下半年整体情况好于上半年"],
        "expected_direction": "up",
        "subcategory": "新品放量预期",
        "memorization_likelihood": "low",
        "target": "唯捷创芯",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688153",
    },
    {
        "candidate_id": "v2_095",
        "category": "industry",
        "sector": "机器人/人工智能应用",
        "key_entities": ["全国人工智能+应用场景创新大会", "机器人交易中心", "智能机器人城市空间应用场景大会"],
        "key_numbers": ["1月23日至25日", "1月23日"],
        "expected_direction": "up",
        "subcategory": "投资日历/产业大会催化",
        "memorization_likelihood": "medium",
        "target": "机器人板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_096",
        "category": "corporate",
        "sector": "PCB/覆铜板",
        "key_entities": ["金安国纪", "上海金板科技", "上海联合产权交易所"],
        "key_numbers": ["60%股权"],
        "expected_direction": "neutral",
        "subcategory": "出售控股子公司股权",
        "memorization_likelihood": "low",
        "target": "金安国纪",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002636",
    },
    {
        "candidate_id": "v2_097",
        "category": "corporate",
        "sector": "精细化工",
        "key_entities": ["怡达股份", "泰兴怡达", "万淇生物科技"],
        "key_numbers": ["吸收合并", "全资子公司"],
        "expected_direction": "neutral",
        "subcategory": "内部吸收合并",
        "memorization_likelihood": "low",
        "target": "怡达股份",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_098",
        "category": "industry",
        "sector": "高价股/科技成长",
        "key_entities": ["寒武纪-U", "贵州茅台", "源杰科技", "北方华创"],
        "key_numbers": ["222只", "219只", "1400元", "500元"],
        "expected_direction": "up",
        "subcategory": "高价股创历史新高",
        "memorization_likelihood": "medium",
        "target": "科技高价股板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_099",
        "category": "corporate",
        "sector": "再生铝/监管风险",
        "key_entities": ["顺博合金", "重庆证监局", "王真见"],
        "key_numbers": ["1429.02万元"],
        "expected_direction": "down",
        "subcategory": "监管处罚/信披违规",
        "memorization_likelihood": "low",
        "target": "顺博合金",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002996",
    },
    {
        "candidate_id": "v2_100",
        "category": "industry",
        "sector": "人工智能/算力",
        "key_entities": ["中证人工智能主题指数", "人工智能ETF", "东吴证券"],
        "key_numbers": ["1.9%", "近8亿元"],
        "expected_direction": "up",
        "subcategory": "AI主题活跃",
        "memorization_likelihood": "medium",
        "target": "中证人工智能主题指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_101",
        "category": "industry",
        "sector": "商业航天",
        "key_entities": ["蓝箭航天", "金风科技", "联创光电", "中国卫星"],
        "key_numbers": ["75亿元"],
        "expected_direction": "up",
        "subcategory": "商业航天IPO催化",
        "memorization_likelihood": "medium",
        "target": "商业航天板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_102",
        "category": "corporate",
        "sector": "家居电商",
        "key_entities": ["趣睡科技", "陈亚强", "徐晓斌", "趣同趣"],
        "key_numbers": ["完成减持计划"],
        "expected_direction": "neutral",
        "subcategory": "减持计划完成",
        "memorization_likelihood": "low",
        "target": "趣睡科技",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_103",
        "category": "industry",
        "sector": "短线连板情绪/题材轮动",
        "key_entities": ["广宇集团", "石英股份", "新赛股份"],
        "key_numbers": ["103股涨停", "13只", "27.78%", "超4500只个股上涨"],
        "expected_direction": "down",
        "subcategory": "连板情绪降温",
        "memorization_likelihood": "low",
        "target": "广宇集团",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002133",
    },
    {
        "candidate_id": "v2_104",
        "category": "corporate",
        "sector": "ST重组/船舶制造",
        "key_entities": ["*ST松发", "恒力造船", "VLCC"],
        "key_numbers": ["4艘", "4-6亿美元"],
        "expected_direction": "up",
        "subcategory": "重大造船合同",
        "memorization_likelihood": "medium",
        "target": "*ST松发",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_106",
        "category": "corporate",
        "sector": "建筑装饰/新城建",
        "key_entities": ["德才股份", "新城建", "新基建", "青岛虚拟现实研究院"],
        "key_numbers": ["全建筑产业链"],
        "expected_direction": "up",
        "subcategory": "机构调研战略表态",
        "memorization_likelihood": "low",
        "target": "德才股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh605287",
    },
    {
        "candidate_id": "v2_107",
        "category": "corporate",
        "sector": "创新药/肿瘤",
        "key_entities": ["奥赛康", "ASKC202", "ESMO", "利厄替尼"],
        "key_numbers": ["2025年10月18日"],
        "expected_direction": "up",
        "subcategory": "创新药临床数据披露",
        "memorization_likelihood": "medium",
        "target": "奥赛康",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_109",
        "category": "macro",
        "sector": "资金面/A股流动性",
        "key_entities": ["逆回购", "MLF", "财通证券", "天风证券"],
        "key_numbers": ["超22000亿元", "8524亿元", "14000亿元", "3000亿元"],
        "expected_direction": "down",
        "subcategory": "流动性收紧前瞻",
        "memorization_likelihood": "medium",
        "target": "沪深300指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_110",
        "category": "industry",
        "sector": "AI语音/开源模型",
        "key_entities": ["阿里通义", "Fun-CosyVoice3-0.5B", "Fun-ASR-Nano"],
        "key_numbers": ["3秒以上", "0.5B", "0.8B"],
        "expected_direction": "up",
        "subcategory": "开源语音模型发布",
        "memorization_likelihood": "medium",
        "target": "AI语音应用板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_111",
        "category": "corporate",
        "sector": "创新药/肾病",
        "key_entities": ["恒瑞医药", "成都盛迪医药", "HRS-5965", "国家药监局药审中心"],
        "key_numbers": ["1类", "7日", "1.42亿元"],
        "expected_direction": "up",
        "subcategory": "突破性治疗认定",
        "memorization_likelihood": "low",
        "target": "恒瑞医药",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600276",
    },
    {
        "candidate_id": "v2_112",
        "category": "industry",
        "sector": "红利资产/分红",
        "key_entities": ["Wind", "上市公司中期分红", "中期分红"],
        "key_numbers": ["1083家公司", "7661.69亿元", "超300家公司"],
        "expected_direction": "up",
        "subcategory": "中期分红扩容",
        "memorization_likelihood": "medium",
        "target": "中证红利指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_113",
        "category": "corporate",
        "sector": "医疗流通/短线炒作",
        "key_entities": ["合富中国", "停牌核查", "股价异常上涨"],
        "key_numbers": ["13天12板", "230.84%", "22.10元/股"],
        "expected_direction": "down",
        "subcategory": "异动风险提示",
        "memorization_likelihood": "medium",
        "target": "合富中国",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_114",
        "category": "industry",
        "sector": "三季报/电子",
        "key_entities": ["A股上市公司", "电子行业", "人工智能"],
        "key_numbers": ["360家", "254家", "七成以上", "32家"],
        "expected_direction": "up",
        "subcategory": "三季报业绩景气",
        "memorization_likelihood": "medium",
        "target": "电子板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_115",
        "category": "corporate",
        "sector": "ST摘帽/影视文旅",
        "key_entities": ["*ST文投", "中兴财光华会计师事务所", "上海证券交易所"],
        "key_numbers": ["2024年度期末净资产为正"],
        "expected_direction": "up",
        "subcategory": "申请撤销风险警示",
        "memorization_likelihood": "low",
        "target": "*ST文投",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600715",
    },
    {
        "candidate_id": "v2_116",
        "category": "corporate",
        "sector": "光伏/债转股",
        "key_entities": ["华民股份", "鸿新新能源", "晶澳无锡"],
        "key_numbers": ["20000万元", "10亿元", "73.74%", "70687.50万元"],
        "expected_direction": "up",
        "subcategory": "债转股增资扩股",
        "memorization_likelihood": "medium",
        "target": "华民股份",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_117",
        "category": "industry",
        "sector": "新三板转板/科创板",
        "key_entities": ["新三板", "龙软科技", "华特气体", "科创板"],
        "key_numbers": ["43家", "14家", "49家", "111家"],
        "expected_direction": "up",
        "subcategory": "转板与IPO热度升温",
        "memorization_likelihood": "medium",
        "target": "华特气体",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688268",
    },
    {
        "candidate_id": "v2_118",
        "category": "corporate",
        "sector": "食品营养/监管风险",
        "key_entities": ["嘉必优", "湖北证监局", "易德伟"],
        "key_numbers": ["2022年度业绩快报", "9月6日"],
        "expected_direction": "down",
        "subcategory": "警示函/信披违规",
        "memorization_likelihood": "low",
        "target": "嘉必优",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688089",
    },
    {
        "candidate_id": "v2_119",
        "category": "industry",
        "sector": "消费芯片/科创板",
        "key_entities": ["南芯科技", "聚辰股份", "格科微", "艾为电子"],
        "key_numbers": ["2024年半年度", "9月10日"],
        "expected_direction": "up",
        "subcategory": "消费芯片业绩说明会",
        "memorization_likelihood": "medium",
        "target": "南芯科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688484",
    },
    {
        "candidate_id": "v2_120",
        "category": "corporate",
        "sector": "白酒/ST风险",
        "key_entities": ["海南椰岛", "退市风险警示", "其他风险警示"],
        "key_numbers": ["1.75亿元"],
        "expected_direction": "down",
        "subcategory": "实施退市风险警示",
        "memorization_likelihood": "low",
        "target": "海南椰岛",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600238",
    },
    {
        "candidate_id": "v2_121",
        "category": "industry",
        "sector": "太空算力",
        "key_entities": ["中国信息通信研究院", "星算·智联", "太空算力研讨会"],
        "key_numbers": ["1月26日"],
        "expected_direction": "up",
        "subcategory": "投资日历/太空算力催化",
        "memorization_likelihood": "medium",
        "target": "太空算力板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_123",
        "category": "industry",
        "sector": "XR/VR",
        "key_entities": ["AWE Asia 2026", "XR产业"],
        "key_numbers": ["2月2日至4日", "2026年春运"],
        "expected_direction": "up",
        "subcategory": "投资日历/XR展会催化",
        "memorization_likelihood": "medium",
        "target": "XR/VR板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_124",
        "category": "corporate",
        "sector": "机场物流",
        "key_entities": ["深圳机场", "快件中心", "深国际全程物流"],
        "key_numbers": ["1%股权", "380.74万元", "50%提升至51%"],
        "expected_direction": "up",
        "subcategory": "收购少数股权并并表",
        "memorization_likelihood": "low",
        "target": "深圳机场",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_125",
        "category": "macro",
        "sector": "A股宽基",
        "key_entities": ["中证A500指数", "A500ETF易方达", "沪深300指数"],
        "key_numbers": ["超5300只个股收涨", "2.9%", "30亿元"],
        "expected_direction": "up",
        "subcategory": "宽基反攻放量",
        "memorization_likelihood": "medium",
        "target": "中证A500指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000510",
        "same_day": True,
    },
    {
        "candidate_id": "v2_126",
        "category": "corporate",
        "sector": "维生素/医药",
        "key_entities": ["广济药业", "股票交易异常波动", "控股股东"],
        "key_numbers": ["连续三个交易日", "涨幅偏离值累计超过20%"],
        "expected_direction": "down",
        "subcategory": "异动澄清",
        "memorization_likelihood": "medium",
        "target": "广济药业",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_127",
        "category": "corporate",
        "sector": "工业气体/半导体",
        "key_entities": ["广钢气体", "合肥启航恒鑫基金", "半导体"],
        "key_numbers": ["4950万元", "5.14%"],
        "expected_direction": "up",
        "subcategory": "产业基金投资",
        "memorization_likelihood": "low",
        "target": "广钢气体",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688548",
    },
    {
        "candidate_id": "v2_128",
        "category": "corporate",
        "sector": "电磁屏蔽/吸波材料",
        "key_entities": ["隆扬电子", "威斯双联"],
        "key_numbers": ["1.2亿元", "51%股权"],
        "expected_direction": "up",
        "subcategory": "并购控股子公司",
        "memorization_likelihood": "low",
        "target": "隆扬电子",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz301389",
    },
    {
        "candidate_id": "v2_129",
        "category": "industry",
        "sector": "创业板/科技成长",
        "key_entities": ["创业板指", "指南针", "东方财富", "同花顺"],
        "key_numbers": ["一度涨近2%", "20亿元", "31.1倍"],
        "expected_direction": "up",
        "subcategory": "午后指数拉升",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sz399006",
    },
]


SKIPPED = [
    {"id": "v2_105", "reason": "审计改聘潮是市场统计汇总，未给出单一、可验证的A股交易目标。"},
    {"id": "v2_108", "reason": "终止审核对象为未上市公司，公告本身缺少明确A股映射标的。"},
    {"id": "v2_122", "reason": "字节跳动总部迁址传闻为海外公司层面事件，对A股仅存在过长的概念映射链条。"},
]


def main() -> None:
    full_map = load_candidates()
    test_cases = []
    for offset, meta in enumerate(KEPT, start=187):
        candidate_id = meta["candidate_id"]
        source = full_map[candidate_id]
        test_cases.append(build_test_case(offset, meta, source))

    output = {"test_cases": test_cases, "skipped": SKIPPED}
    OUTPUT_PATH.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(test_cases)} test cases to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
