from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from annotate_v2_batch_1 import build_test_case, load_candidates


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data" / "seed" / "v2_annotated_2.json"


KEPT: list[dict[str, Any]] = [
    {
        "candidate_id": "v2_044",
        "category": "industry",
        "sector": "电力/算力轮动",
        "key_entities": ["鸿博股份", "华银电力", "算力产业链", "电力企业"],
        "key_numbers": ["超4100只个股下跌", "1.06万亿", "3连板"],
        "expected_direction": "up",
        "subcategory": "行情回顾中的强势主线",
        "memorization_likelihood": "medium",
        "target": "华银电力",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600744",
    },
    {
        "candidate_id": "v2_045",
        "category": "industry",
        "sector": "具身智能/红利资产",
        "key_entities": ["中信建投", "人形机器人", "机器狗", "红利资产"],
        "key_numbers": ["低估值", "高股息率", "H股发行计划"],
        "expected_direction": "up",
        "subcategory": "券商风格研判",
        "memorization_likelihood": "medium",
        "target": "中证红利指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000922",
    },
    {
        "candidate_id": "v2_046",
        "category": "industry",
        "sector": "年报业绩预告",
        "key_entities": ["Wind", "A股上市公司", "业绩预告"],
        "key_numbers": ["108家", "60家预喜", "55.56%", "18家公司净利润翻倍"],
        "expected_direction": "up",
        "subcategory": "业绩预告统计",
        "memorization_likelihood": "medium",
        "target": "业绩预喜板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_047",
        "category": "industry",
        "sector": "半导体晶圆代工/成熟制程",
        "key_entities": ["TrendForce", "8英寸晶圆厂", "IC设计厂", "IDM厂"],
        "key_numbers": ["50%至60%", "2023年下半年"],
        "expected_direction": "down",
        "subcategory": "产能利用率下滑",
        "memorization_likelihood": "medium",
        "target": "中芯国际",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688981",
    },
    {
        "candidate_id": "v2_048",
        "category": "corporate",
        "sector": "环境监测/物联网",
        "key_entities": ["碧兴物联", "丰图汇烝"],
        "key_numbers": ["235.56万股", "3%", "1%", "2%"],
        "expected_direction": "down",
        "subcategory": "股东减持计划",
        "memorization_likelihood": "low",
        "target": "碧兴物联",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_049",
        "category": "corporate",
        "sector": "智慧物流/公路港",
        "key_entities": ["传化智联", "传化物流", "温州途邦", "温州传化公路港"],
        "key_numbers": ["90%股权", "1.92亿元"],
        "expected_direction": "neutral",
        "subcategory": "股权及债权转让",
        "memorization_likelihood": "low",
        "target": "传化智联",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_050",
        "category": "corporate",
        "sector": "半导体设备/安检",
        "key_entities": ["光力科技", "李祖庆"],
        "key_numbers": ["656,000股", "0.19%", "三个月内"],
        "expected_direction": "down",
        "subcategory": "高管减持计划",
        "memorization_likelihood": "low",
        "target": "光力科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300480",
    },
    {
        "candidate_id": "v2_051",
        "category": "industry",
        "sector": "短线连板/资产重组",
        "key_entities": ["凤凰光学", "滨海能源", "新中港"],
        "key_numbers": ["5天4板3连板", "竞价涨停", "高开5.68%"],
        "expected_direction": "up",
        "subcategory": "开盘竞价情绪",
        "memorization_likelihood": "low",
        "target": "凤凰光学",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600071",
    },
    {
        "candidate_id": "v2_052",
        "category": "policy",
        "sector": "互联网营销/电子发票服务",
        "key_entities": ["央视315晚会", "兑吧网络科技", "诺诺网", "消费陷阱"],
        "key_numbers": ["一天流水20亿元", "200元话费券", "4000元", "15个月"],
        "expected_direction": "down",
        "subcategory": "315曝光/合规风险",
        "memorization_likelihood": "medium",
        "target": "航天信息",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600271",
    },
    {
        "candidate_id": "v2_053",
        "category": "industry",
        "sector": "煤炭/高股息",
        "key_entities": ["国泰君安", "煤炭价格", "高股息资产"],
        "key_numbers": ["950元/吨", "下周煤价回升"],
        "expected_direction": "up",
        "subcategory": "券商价格研判",
        "memorization_likelihood": "medium",
        "target": "陕西煤业",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh601225",
    },
    {
        "candidate_id": "v2_054",
        "category": "industry",
        "sector": "人工智能/算力",
        "key_entities": ["中信建投", "云计算", "数据资产", "AI芯片设计"],
        "key_numbers": ["第五次通用性技术浪潮"],
        "expected_direction": "up",
        "subcategory": "产业趋势判断",
        "memorization_likelihood": "medium",
        "target": "中科曙光",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh603019",
    },
    {
        "candidate_id": "v2_055",
        "category": "corporate",
        "sector": "海洋油服/工程",
        "key_entities": ["海油工程", "浦项制铁国际", "SHWE气田四期开发"],
        "key_numbers": ["5.23亿美元", "36个月"],
        "expected_direction": "up",
        "subcategory": "海外大额合同",
        "memorization_likelihood": "low",
        "target": "海油工程",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600583",
    },
    {
        "candidate_id": "v2_056",
        "category": "corporate",
        "sector": "压缩机/机器人概念",
        "key_entities": ["海立股份", "基本面未发生重大变化", "重大资产重组"],
        "key_numbers": ["101.40%"],
        "expected_direction": "down",
        "subcategory": "异动风险提示",
        "memorization_likelihood": "medium",
        "target": "海立股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600619",
    },
    {
        "candidate_id": "v2_057",
        "category": "corporate",
        "sector": "配电设备",
        "key_entities": ["双杰电气", "许专"],
        "key_numbers": ["378.9463万股", "0.47%", "15个交易日后3个月内"],
        "expected_direction": "down",
        "subcategory": "董事减持计划",
        "memorization_likelihood": "low",
        "target": "双杰电气",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_058",
        "category": "corporate",
        "sector": "园区开发/REITs",
        "key_entities": ["张江高科", "银河投资", "华安资管", "江河曜宸"],
        "key_numbers": ["不超过1.4亿元", "不超过7亿元"],
        "expected_direction": "up",
        "subcategory": "参投合伙企业",
        "memorization_likelihood": "low",
        "target": "张江高科",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_059",
        "category": "industry",
        "sector": "低空经济/eVTOL",
        "key_entities": ["峰飞航空", "猎鹰航空", "eVTOL", "阿布扎比国家石油公司"],
        "key_numbers": ["50架", "15架", "35架", "2025年底"],
        "expected_direction": "up",
        "subcategory": "海外订单催化",
        "memorization_likelihood": "medium",
        "target": "低空经济板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_060",
        "category": "industry",
        "sector": "芯片半导体",
        "key_entities": ["蓝英装备", "芯片股", "情绪指标"],
        "key_numbers": ["14点快评"],
        "expected_direction": "up",
        "subcategory": "盘中主线强化",
        "memorization_likelihood": "low",
        "target": "蓝英装备",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300293",
    },
    {
        "candidate_id": "v2_061",
        "category": "corporate",
        "sector": "影视传媒/数字内容",
        "key_entities": ["唐德影视", "华智数媒"],
        "key_numbers": ["2025年4月25日"],
        "expected_direction": "neutral",
        "subcategory": "证券简称变更",
        "memorization_likelihood": "low",
        "target": "唐德影视",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300426",
    },
    {
        "candidate_id": "v2_062",
        "category": "corporate",
        "sector": "电力设备/充电桩",
        "key_entities": ["中恒电气", "朱国锭", "刑事判决书"],
        "key_numbers": ["有期徒刑三年", "缓刑四年", "罚金100万元"],
        "expected_direction": "down",
        "subcategory": "实控人涉案判决",
        "memorization_likelihood": "medium",
        "target": "中恒电气",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_063",
        "category": "corporate",
        "sector": "轨交信号/低空经济",
        "key_entities": ["中国通号", "楼齐良", "低空经济"],
        "key_numbers": ["5月7日"],
        "expected_direction": "up",
        "subcategory": "战略推进会",
        "memorization_likelihood": "medium",
        "target": "中国通号",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688009",
    },
    {
        "candidate_id": "v2_064",
        "category": "policy",
        "sector": "上海先进制造业",
        "key_entities": ["上海市人民政府办公厅", "先进制造业转型升级三年行动方案"],
        "key_numbers": ["到2028年", "100家", "500家", "累计超过600家"],
        "expected_direction": "up",
        "subcategory": "地方制造业政策",
        "memorization_likelihood": "medium",
        "target": "上海先进制造业板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_065",
        "category": "industry",
        "sector": "面板/LCD",
        "key_entities": ["Omdia", "液晶电视面板", "大尺寸屏幕订单"],
        "key_numbers": ["年增19%", "1.614亿台", "年增长8%"],
        "expected_direction": "up",
        "subcategory": "面板需求回暖预期",
        "memorization_likelihood": "medium",
        "target": "京东方A",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz000725",
    },
    {
        "candidate_id": "v2_066",
        "category": "corporate",
        "sector": "刀剪五金/消费品",
        "key_entities": ["张小泉", "富春控股集团", "预重整", "控制权变动"],
        "key_numbers": ["2025年3月25日"],
        "expected_direction": "down",
        "subcategory": "间接控股股东预重整",
        "memorization_likelihood": "low",
        "target": "张小泉",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz301055",
    },
    {
        "candidate_id": "v2_067",
        "category": "corporate",
        "sector": "电缆/监管风险",
        "key_entities": ["尚纬股份", "李广胜", "操纵证券期货市场罪"],
        "key_numbers": ["接连跌停"],
        "expected_direction": "down",
        "subcategory": "实控人被刑拘舆情",
        "memorization_likelihood": "medium",
        "target": "尚纬股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh603333",
    },
    {
        "candidate_id": "v2_068",
        "category": "corporate",
        "sector": "动力电池",
        "key_entities": ["孚能科技", "镇江一期", "镇江二期", "赣州基地"],
        "key_numbers": ["8GWh", "16GWh", "13GWh", "2020年下半年"],
        "expected_direction": "up",
        "subcategory": "产能投放进展",
        "memorization_likelihood": "low",
        "target": "孚能科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688567",
    },
    {
        "candidate_id": "v2_069",
        "category": "industry",
        "sector": "算力硬件/PCB",
        "key_entities": ["PCB概念", "液冷服务器", "数据中心电源", "AI眼镜"],
        "key_numbers": ["10余股涨停"],
        "expected_direction": "up",
        "subcategory": "热点主线强化",
        "memorization_likelihood": "medium",
        "target": "方正科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh600601",
    },
    {
        "candidate_id": "v2_070",
        "category": "corporate",
        "sector": "储能/铅酸电池",
        "key_entities": ["南都电源", "控制权变更", "复牌"],
        "key_numbers": ["2025年12月19日"],
        "expected_direction": "down",
        "subcategory": "控制权变更终止",
        "memorization_likelihood": "low",
        "target": "南都电源",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_071",
        "category": "industry",
        "sector": "网络安全/连板情绪",
        "key_entities": ["国华网安", "人民网", "工业富联"],
        "key_numbers": ["41股涨停", "封板率79%", "8天5板"],
        "expected_direction": "up",
        "subcategory": "涨停复盘",
        "memorization_likelihood": "low",
        "target": "国华网安",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz000004",
    },
    {
        "candidate_id": "v2_072",
        "category": "policy",
        "sector": "科创板",
        "key_entities": ["科创板", "公募基金", "境外资金", "机构投资者"],
        "key_numbers": ["开市两年来"],
        "expected_direction": "up",
        "subcategory": "机构化配置深化",
        "memorization_likelihood": "medium",
        "target": "科创50指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000688",
    },
    {
        "candidate_id": "v2_073",
        "category": "corporate",
        "sector": "钛白粉/磷酸铁锂",
        "key_entities": ["龙蟒佰利", "佰利新能源", "河南龙佰新材料", "磷酸铁锂"],
        "key_numbers": ["3亿元"],
        "expected_direction": "up",
        "subcategory": "跨界新能源布局",
        "memorization_likelihood": "medium",
        "target": "龙蟒佰利",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002601",
    },
    {
        "candidate_id": "v2_074",
        "category": "corporate",
        "sector": "ST重整/数字营销",
        "key_entities": ["*ST名家", "退市风险警示", "重整计划"],
        "key_numbers": ["2024年年度报告"],
        "expected_direction": "up",
        "subcategory": "申请撤销退市风险警示",
        "memorization_likelihood": "low",
        "target": "*ST名家",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_075",
        "category": "industry",
        "sector": "商业航天",
        "key_entities": ["中科宇航", "力鸿一号", "亚轨道飞行试验", "返回式载荷舱"],
        "key_numbers": ["近日", "力鸿一号遥一"],
        "expected_direction": "up",
        "subcategory": "试验任务进展",
        "memorization_likelihood": "medium",
        "target": "商业航天板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_076",
        "category": "corporate",
        "sector": "零售信息化/云数据库",
        "key_entities": ["石基零售", "阿里云", "PolarDB", "石基信息"],
        "key_numbers": ["50%成本"],
        "expected_direction": "up",
        "subcategory": "云合作与产品集成",
        "memorization_likelihood": "low",
        "target": "石基信息",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002153",
    },
    {
        "candidate_id": "v2_077",
        "category": "corporate",
        "sector": "能源装备/SMR",
        "key_entities": ["杰瑞股份", "杰瑞中东公司", "SMR", "阿联酋迪拜"],
        "key_numbers": ["1000万阿联酋迪拉姆", "约合1907.10万元人民币"],
        "expected_direction": "up",
        "subcategory": "海外设立SMR子公司",
        "memorization_likelihood": "medium",
        "target": "杰瑞股份",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_078",
        "category": "corporate",
        "sector": "通信设备/科创板IPO",
        "key_entities": ["震有科技", "科创板IPO"],
        "key_numbers": ["16.25元/股", "7月13日"],
        "expected_direction": "up",
        "subcategory": "IPO发行定价",
        "memorization_likelihood": "low",
        "target": "震有科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688418",
    },
    {
        "candidate_id": "v2_079",
        "category": "industry",
        "sector": "科创板",
        "key_entities": ["科创成长指数", "科创板50指数", "科创50ETF"],
        "key_numbers": ["3.5%", "3.0%", "超9亿元", "超720亿元"],
        "expected_direction": "up",
        "subcategory": "指数放量走强",
        "memorization_likelihood": "medium",
        "target": "科创板50指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_080",
        "category": "industry",
        "sector": "存储芯片/NAND",
        "key_entities": ["NAND", "SSD", "QLC", "TLC"],
        "key_numbers": ["环比上月大涨超30%", "两到三倍"],
        "expected_direction": "up",
        "subcategory": "存储涨价",
        "memorization_likelihood": "medium",
        "target": "存储芯片板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_081",
        "category": "corporate",
        "sector": "退市整理",
        "key_entities": ["东通退", "深圳证券交易所", "退市整理期"],
        "key_numbers": ["2026年1月21日", "2026年1月22日"],
        "expected_direction": "down",
        "subcategory": "终止上市摘牌",
        "memorization_likelihood": "low",
        "target": "东通退",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_082",
        "category": "industry",
        "sector": "半导体设备/光刻机",
        "key_entities": ["南方基金", "郑晓曦", "光刻机产业链", "国产替代"],
        "key_numbers": ["2030年", "35%", "60%", "30%以上"],
        "expected_direction": "up",
        "subcategory": "国产替代主题宣传",
        "memorization_likelihood": "medium",
        "target": "光刻机产业链",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_083",
        "category": "policy",
        "sector": "科创板IPO",
        "key_entities": ["证监会", "铁科首钢轨道技术", "瑞联新材料", "苑东生物"],
        "key_numbers": ["3家"],
        "expected_direction": "up",
        "subcategory": "IPO注册获批",
        "memorization_likelihood": "medium",
        "target": "铁科轨道",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688569",
    },
    {
        "candidate_id": "v2_084",
        "category": "corporate",
        "sector": "硬质合金工具",
        "key_entities": ["新锐股份", "网下配售限售股"],
        "key_numbers": ["112.70万股", "6个月", "2022年4月27日"],
        "expected_direction": "down",
        "subcategory": "限售股解禁",
        "memorization_likelihood": "low",
        "target": "新锐股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688257",
    },
    {
        "candidate_id": "v2_085",
        "category": "macro",
        "sector": "创业板/科技成长",
        "key_entities": ["创业板ETF易方达", "华西证券", "科技产业扩散", "年报业绩预告"],
        "key_numbers": ["创业板中盘200指数下跌0.5%", "创业板指数下跌0.7%", "创业板成长指数下跌0.9%"],
        "expected_direction": "up",
        "subcategory": "宽基配置观点",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_086",
        "category": "industry",
        "sector": "广东半导体",
        "key_entities": ["广东省集成电路行业协会", "广州粤芯半导体", "中国集成电路制造年会"],
        "key_numbers": ["第23届"],
        "expected_direction": "up",
        "subcategory": "产业协会成立",
        "memorization_likelihood": "medium",
        "target": "风华高科",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz000636",
    },
]


SKIPPED: list[dict[str, str]] = []


def main() -> None:
    full_map = load_candidates()
    test_cases = []
    for offset, meta in enumerate(KEPT, start=144):
        candidate_id = meta["candidate_id"]
        source = full_map[candidate_id]
        test_cases.append(build_test_case(offset, meta, source))

    output = {"test_cases": test_cases, "skipped": SKIPPED}
    OUTPUT_PATH.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(test_cases)} test cases to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
