from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from annotate_v2_batch_1 import build_test_case, load_candidates


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "data" / "seed" / "v2_annotated_4.json"


KEPT: list[dict[str, Any]] = [
    {
        "candidate_id": "v2_130",
        "category": "industry",
        "sector": "MR头显/苹果链",
        "key_entities": ["郭明錤", "苹果", "AR/MR头显", "iPhone 15"],
        "key_numbers": ["2025年", "第二代两个机型"],
        "expected_direction": "up",
        "subcategory": "苹果MR新品预期催化",
        "memorization_likelihood": "medium",
        "target": "歌尔股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002241",
    },
    {
        "candidate_id": "v2_131",
        "category": "industry",
        "sector": "短线连板/数据中心电源",
        "key_entities": ["电光科技", "顺钠股份", "海得控制", "美邦股份"],
        "key_numbers": ["13天9板", "9天8板", "竞价涨停", "高开5.93%"],
        "expected_direction": "up",
        "subcategory": "开盘竞价情绪",
        "memorization_likelihood": "low",
        "target": "电光科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002730",
    },
    {
        "candidate_id": "v2_132",
        "category": "industry",
        "sector": "科创板/半导体",
        "key_entities": ["科创板50指数", "寒武纪-U", "海光信息", "科创板50ETF"],
        "key_numbers": ["涨超1%", "超10亿元", "726亿元"],
        "expected_direction": "up",
        "subcategory": "午后指数拉升",
        "memorization_likelihood": "medium",
        "target": "科创50指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_133",
        "category": "industry",
        "sector": "次新股",
        "key_entities": ["顺控发展", "迎丰股份", "法狮龙", "王力安防"],
        "key_numbers": ["跌停", "2连板", "地天板"],
        "expected_direction": "down",
        "subcategory": "次新股退潮",
        "memorization_likelihood": "low",
        "target": "迎丰股份",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh605055",
    },
    {
        "candidate_id": "v2_135",
        "category": "corporate",
        "sector": "军工/人工影响天气",
        "key_entities": ["中天火箭", "航天彩虹", "人工影响天气子公司"],
        "key_numbers": ["5000万元", "80%"],
        "expected_direction": "up",
        "subcategory": "关联方设立控股子公司",
        "memorization_likelihood": "low",
        "target": "中天火箭",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_137",
        "category": "industry",
        "sector": "消费复苏/AI分歧",
        "key_entities": ["拓维信息", "鸿博股份", "CPO", "酿酒"],
        "key_numbers": ["跌超5%", "再创新高"],
        "expected_direction": "down",
        "subcategory": "AI高位分歧",
        "memorization_likelihood": "medium",
        "target": "拓维信息",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002261",
    },
    {
        "candidate_id": "v2_138",
        "category": "corporate",
        "sector": "传媒投资/股权基金",
        "key_entities": ["中文传媒", "蓝海国投", "平安资本", "平泰股权投资"],
        "key_numbers": ["1.67亿元", "0.30亿元", "17.9641%", "5.37亿元"],
        "expected_direction": "neutral",
        "subcategory": "认购私募股权基金",
        "memorization_likelihood": "low",
        "target": "中文传媒",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_139",
        "category": "corporate",
        "sector": "ST餐饮/治理",
        "key_entities": ["*ST云网", "徐小舸", "第六届董事会"],
        "key_numbers": ["独立董事", "三分之一"],
        "expected_direction": "neutral",
        "subcategory": "独立董事辞职",
        "memorization_likelihood": "low",
        "target": "*ST云网",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_140",
        "category": "macro",
        "sector": "创业板/成长风格",
        "key_entities": ["上证报", "上证综指", "创业板指"],
        "key_numbers": ["2021年7月14日"],
        "expected_direction": "down",
        "subcategory": "官媒风险提示",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sz399006",
    },
    {
        "candidate_id": "v2_141",
        "category": "industry",
        "sector": "科创板/算力",
        "key_entities": ["科创50指数", "科创200指数", "华安证券", "算力端"],
        "key_numbers": ["-1.2%", "-1.7%", "0.26%", "0.66%"],
        "expected_direction": "up",
        "subcategory": "科创板回调中的算力看多",
        "memorization_likelihood": "medium",
        "target": "科创50指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_142",
        "category": "macro",
        "sector": "AI应用/机器人/磷化工",
        "key_entities": ["沪指", "恒信东方", "柯力传感", "有研新材"],
        "key_numbers": ["0.66%", "超170股涨停", "1.61万亿", "15只涨停晋级"],
        "expected_direction": "up",
        "subcategory": "放量普涨收评",
        "memorization_likelihood": "medium",
        "target": "沪深300指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000300",
        "same_day": True,
    },
    {
        "candidate_id": "v2_143",
        "category": "industry",
        "sector": "具身智能/机器人",
        "key_entities": ["智元机器人", "灵犀X2", "彭志辉"],
        "key_numbers": ["第5000台", "1846台", "1742台", "1412台"],
        "expected_direction": "up",
        "subcategory": "具身机器人量产交付",
        "memorization_likelihood": "medium",
        "target": "机器人板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_144",
        "category": "corporate",
        "sector": "电解液/诉讼纠纷",
        "key_entities": ["永太科技", "邵武永太", "天赐材料"],
        "key_numbers": ["5752万元", "2025年7月3日"],
        "expected_direction": "neutral",
        "subcategory": "诉讼维权",
        "memorization_likelihood": "low",
        "target": "永太科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002326",
    },
    {
        "candidate_id": "v2_145",
        "category": "corporate",
        "sector": "电子元件/监管风险",
        "key_entities": ["惠伦晶体", "赵积清", "证监会"],
        "key_numbers": ["5.34%", "5416.55万股", "1346.03万股"],
        "expected_direction": "down",
        "subcategory": "信披违法违规立案",
        "memorization_likelihood": "low",
        "target": "惠伦晶体",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300460",
    },
    {
        "candidate_id": "v2_146",
        "category": "corporate",
        "sector": "网络安全/治理修复",
        "key_entities": ["中孚信息", "孙强", "武汉市硚口区监察委员会"],
        "key_numbers": ["2025年4月7日", "2025年8月27日"],
        "expected_direction": "up",
        "subcategory": "解除留置",
        "memorization_likelihood": "low",
        "target": "中孚信息",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300659",
    },
    {
        "candidate_id": "v2_147",
        "category": "industry",
        "sector": "AIGC/AI应用",
        "key_entities": ["万兴科技", "开普云", "鸿博股份", "中文在线"],
        "key_numbers": ["涨超10%", "1100亿美元", "2030年"],
        "expected_direction": "up",
        "subcategory": "AIGC板块走强",
        "memorization_likelihood": "medium",
        "target": "万兴科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz300624",
    },
    {
        "candidate_id": "v2_148",
        "category": "industry",
        "sector": "核聚变/电力需求",
        "key_entities": ["孙玄", "中国科学技术大学", "星能玄光", "核聚变"],
        "key_numbers": ["1.5%", "20%", "2025 Inclusion·外滩大会"],
        "expected_direction": "up",
        "subcategory": "核聚变主题催化",
        "memorization_likelihood": "medium",
        "target": "融发核电",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002366",
    },
    {
        "candidate_id": "v2_149",
        "category": "corporate",
        "sector": "特种高分子材料",
        "key_entities": ["常青科技", "特种高分子单体二期"],
        "key_numbers": ["2025年5月底", "七期"],
        "expected_direction": "up",
        "subcategory": "项目正式投产",
        "memorization_likelihood": "low",
        "target": "常青科技",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_150",
        "category": "industry",
        "sector": "AI医疗",
        "key_entities": ["润达医疗", "塞力医疗", "华为", "医疗卫生军团"],
        "key_numbers": ["涨停", "涨超10%"],
        "expected_direction": "up",
        "subcategory": "AI医疗催化",
        "memorization_likelihood": "medium",
        "target": "润达医疗",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh603108",
    },
    {
        "candidate_id": "v2_151",
        "category": "industry",
        "sector": "红利资产/A股分红",
        "key_entities": ["A股上市公司", "现金分红"],
        "key_numbers": ["2.56万亿元", "截至12月15日"],
        "expected_direction": "up",
        "subcategory": "分红生态强化",
        "memorization_likelihood": "medium",
        "target": "红利股板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_152",
        "category": "industry",
        "sector": "机器人/具身智能",
        "key_entities": ["机器人产业指数", "宇树机器人", "特斯拉", "Optimus V3"],
        "key_numbers": ["4.4%", "3.3亿份", "24亿元", "100万台"],
        "expected_direction": "up",
        "subcategory": "机器人指数放量上涨",
        "memorization_likelihood": "medium",
        "target": "埃斯顿",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002747",
    },
    {
        "candidate_id": "v2_153",
        "category": "industry",
        "sector": "稀土永磁/人形机器人",
        "key_entities": ["英洛华", "大地熊", "中科三环", "中金公司"],
        "key_numbers": ["涨停", "大涨10%"],
        "expected_direction": "up",
        "subcategory": "稀土永磁异动",
        "memorization_likelihood": "low",
        "target": "英洛华",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz000795",
    },
    {
        "candidate_id": "v2_154",
        "category": "corporate",
        "sector": "医药/新冠治疗",
        "key_entities": ["上海医药", "羟氯喹", "9家医疗机构", "陈凯先"],
        "key_numbers": ["9家", "超76%"],
        "expected_direction": "up",
        "subcategory": "疫情药物临床试验",
        "memorization_likelihood": "medium",
        "target": "上海医药",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh601607",
    },
    {
        "candidate_id": "v2_155",
        "category": "corporate",
        "sector": "机器人材料/风险提示",
        "key_entities": ["上纬新材", "具身智能机器人", "样机产出"],
        "key_numbers": ["2026年度", "宣发初期"],
        "expected_direction": "down",
        "subcategory": "机器人业务风险提示",
        "memorization_likelihood": "medium",
        "target": "上纬新材",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_157",
        "category": "industry",
        "sector": "军工/ChatGPT修复",
        "key_entities": ["创业板指", "军工", "CPO", "ChatGPT"],
        "key_numbers": ["不足10只", "3310", "5日线"],
        "expected_direction": "down",
        "subcategory": "短线情绪冰点",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sz399006",
    },
    {
        "candidate_id": "v2_158",
        "category": "industry",
        "sector": "钨/高端制造材料",
        "key_entities": ["钨价", "仲钨酸铵", "光伏钨丝", "新能源汽车电机"],
        "key_numbers": ["100万元/吨", "2月9日"],
        "expected_direction": "up",
        "subcategory": "钨价上涨催化",
        "memorization_likelihood": "medium",
        "target": "中钨高新",
        "target_type": "company",
    },
    {
        "candidate_id": "v2_159",
        "category": "corporate",
        "sector": "有机硅/化工",
        "key_entities": ["鲁西化工", "100万吨/年有机硅项目", "一期工程"],
        "key_numbers": ["40万吨/年", "100万吨/年"],
        "expected_direction": "up",
        "subcategory": "产能投产",
        "memorization_likelihood": "low",
        "target": "鲁西化工",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz000830",
    },
    {
        "candidate_id": "v2_160",
        "category": "macro",
        "sector": "A股宽基",
        "key_entities": ["中国银河证券", "中证A500指数", "中证A100指数"],
        "key_numbers": ["-2.3%", "-2.6%", "10月"],
        "expected_direction": "up",
        "subcategory": "券商看多宽基",
        "memorization_likelihood": "medium",
        "target": "中证A500指数",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_161",
        "category": "corporate",
        "sector": "高端机床/并购",
        "key_entities": ["汇洲智能", "上海航天壹亘", "上海联合产权交易所"],
        "key_numbers": ["75%股权", "6341.1375万元"],
        "expected_direction": "up",
        "subcategory": "参与竞拍优质资产",
        "memorization_likelihood": "low",
        "target": "汇洲智能",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002122",
    },
    {
        "candidate_id": "v2_162",
        "category": "corporate",
        "sector": "医药制剂",
        "key_entities": ["华纳药厂", "卡前列素氨丁三醇注射液", "国家药监局"],
        "key_numbers": ["13周至20周"],
        "expected_direction": "up",
        "subcategory": "药品注册获批",
        "memorization_likelihood": "low",
        "target": "华纳药厂",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688799",
    },
    {
        "candidate_id": "v2_163",
        "category": "industry",
        "sector": "晶圆代工/半导体",
        "key_entities": ["Strategy Analytics", "台积电", "中芯国际", "三星"],
        "key_numbers": ["200亿美元", "2022年Q3"],
        "expected_direction": "up",
        "subcategory": "全球代工景气验证",
        "memorization_likelihood": "medium",
        "target": "中芯国际",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sh688981",
    },
    {
        "candidate_id": "v2_165",
        "category": "industry",
        "sector": "商业航天/AI硬件调整",
        "key_entities": ["工业富联", "商业航天", "军工", "锂矿"],
        "key_numbers": ["超2800亿", "跌停"],
        "expected_direction": "down",
        "subcategory": "缩量整理/等待转强",
        "memorization_likelihood": "medium",
        "target": "创业板指",
        "target_type": "index",
    },
    {
        "candidate_id": "v2_166",
        "category": "industry",
        "sector": "AI手机/消费电子",
        "key_entities": ["DIGITIMES", "AI手机", "生成式AI安卓手机", "5G网络"],
        "key_numbers": ["12.213亿台", "2.3%", "4.458亿台", "近6亿台"],
        "expected_direction": "up",
        "subcategory": "AI手机出货预测",
        "memorization_likelihood": "medium",
        "target": "消费电子板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_167",
        "category": "industry",
        "sector": "芯片半导体/大金融",
        "key_entities": ["科创50指数", "中芯国际", "寒武纪", "金融街论坛"],
        "key_numbers": ["涨超11%", "2.1万亿元", "6064亿", "17家"],
        "expected_direction": "up",
        "subcategory": "行情回顾中的芯片主线",
        "memorization_likelihood": "medium",
        "target": "科创50指数",
        "target_type": "index",
        "proxy_kind": "index",
        "proxy_symbol": "sh000688",
    },
    {
        "candidate_id": "v2_168",
        "category": "industry",
        "sector": "HBM/存储芯片",
        "key_entities": ["三星电子", "英伟达", "12层HBM3E", "SK海力士"],
        "key_numbers": ["12层", "9月", "8层"],
        "expected_direction": "up",
        "subcategory": "HBM供给催化",
        "memorization_likelihood": "medium",
        "target": "雅克科技",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002409",
    },
    {
        "candidate_id": "v2_169",
        "category": "industry",
        "sector": "券商调研/科技成长",
        "key_entities": ["A股公司", "电力设备", "化工", "券商资管机构"],
        "key_numbers": ["440家", "超1000家"],
        "expected_direction": "up",
        "subcategory": "券商调研热度",
        "memorization_likelihood": "medium",
        "target": "科技成长板块",
        "target_type": "sector",
    },
    {
        "candidate_id": "v2_170",
        "category": "corporate",
        "sector": "ST重组/医药制造",
        "key_entities": ["ST天圣", "深交所", "口服固体制剂数字化工厂"],
        "key_numbers": ["11月4日", "单主业"],
        "expected_direction": "up",
        "subcategory": "重组后经营聚焦",
        "memorization_likelihood": "low",
        "target": "ST天圣",
        "target_type": "company",
        "proxy_kind": "company",
        "proxy_symbol": "sz002872",
    },
]


SKIPPED = [
    {"id": "v2_134", "reason": "并购主体为非A股上市公司，新闻未给出可直接映射的A股交易标的。"},
    {"id": "v2_136", "reason": "港股午盘与港股个股波动摘要，缺少明确直接的A股目标。"},
    {"id": "v2_156", "reason": "融资主体为未上市存储公司，缺少直接A股标的。"},
    {"id": "v2_164", "reason": "任天堂主机销量对应海外公司，A股映射链条偏长且缺少直接目标。"},
]


def main() -> None:
    full_map = load_candidates()
    test_cases = []
    for offset, meta in enumerate(KEPT, start=230):
        source = full_map[meta["candidate_id"]]
        test_cases.append(build_test_case(offset, meta, source))

    output = {"test_cases": test_cases, "skipped": SKIPPED}
    OUTPUT_PATH.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(test_cases)} test cases to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
